<a href="https://colab.research.google.com/github/aryan-327/IML-LAB/blob/main/exp3_q1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

X = np.array([[1,2],[1,3],[1,4]])
y = np.array([[1],[2],[3]])

print("Design matrix X:")
print(X)
print("\nTarget vector y:")
print(y)

Design matrix X:
[[1 2]
 [1 3]
 [1 4]]

Target vector y:
[[1]
 [2]
 [3]]


In [ ]:
X_transpose = X.T
Xt_X = np.dot(X_transpose, X)

lambda_val = 1

# User-defined 'I' matrix
I = np.array([[0,0],[0,1]])

regularization_term = lambda_val * I

regularized_term = Xt_X + regularization_term

print("X_transpose:")
print(X_transpose)
print("\nXt_X:")
print(Xt_X)
print("\nLambda value:", lambda_val)
print("\nUser-defined matrix I:")
print(I)
print("\nRegularization term (lambda * I):")
print(regularization_term)
print("\nRegularized term (Xt_X + lambda * I):")
print(regularized_term)

X_transpose:
[[1 1 1]
 [2 3 4]]

Xt_X:
[[ 3  9]
 [ 9 29]]

Lambda value: 1

User-defined matrix I:
[[0 0]
 [0 1]]

Regularization term (lambda * I):
[[0 0]
 [0 1]]

Regularized term (Xt_X + lambda * I):
[[ 3  9]
 [ 9 30]]


In [ ]:
inverse_regularized_term = np.linalg.inv(regularized_term)

print("Inverse of (Xt_X + lambda * I):")
print(inverse_regularized_term)

Inverse of (Xt_X + lambda * I):
[[ 3.33333333 -1.        ]
 [-1.          0.33333333]]


In [ ]:
Xt_y = np.dot(X_transpose, y)

print("X_transpose * y (Xt_y):")
print(Xt_y)

X_transpose * y (Xt_y):
[[ 6]
 [20]]


In [ ]:
ridge_coefficients = np.dot(inverse_regularized_term, Xt_y)

print("Ridge Regression Coefficients (beta):")
# Display coefficients in decimal format without scientific notation
np.set_printoptions(suppress=True, formatter={'float_kind':'{:0.8f}'.format})
print(ridge_coefficients)

Ridge Regression Coefficients (beta):
[[-0.00000000]
 [0.66666667]]
